### ISSUE TITLE
$global.marked is undefined

### ISSUE THREAD

**Issue by ankit-fourtek** [marwan-at-work/marwanio#4]
The page is not loading and showing log ie.
$global.marked is undefined in marked.go file.

Please help me out.

**Comment by marwan-at-work** [comment]
@ankit-fourtek thanks for reporting this. It turns out the new `webpack` requires `path` to be present in the config otherwise it will not output `libs.inc.js` which puts `marked` in the $global object. Feel free to pull my latest commit and try again. Let me know if it doesn't work still : )
