### ISSUE TITLE
Usability thought: links can't be right clicked and opened in new tab/window

### ISSUE THREAD

**Issue by justinclift** [marwan-at-work/marwanio#5]
Noticed something fairly non-optimal.  None of the links (eg to "Blog" or pages in it) are clickable.

So (when using Firefox), middle clicking to open the link in a new tab doesn't work, nor does right clicking to show the context menu.  Guessing it's a simple fix - eg putting the link url into some dom attribute - but haven't taken the time to check. :wink:

**Comment by marwan-at-work** [comment]
@justinclift It seems to work for me (firefox/chrome/safari). Is that happening when you run the server locally or by visiting https://www.marwan.io 

thank you or reporting it!

**Comment by marwan-at-work** [comment]
@justinclift I see what you mean now, I thought you said non of the links are clickable at all.

As you hinted, the `href` tag is missing from the links. So I updated the router as well as the app. It should work now, thanks again for taking a look! 

PS. It might take a cmd+shift+R to properly remove the cached javascript to see the change deployed.

**Comment by dmitshur** [comment]
I can confirm the fix works for me. Thanks!

**Comment by justinclift** [comment]
> @justinclift I see what you mean now, I thought you said non of the links are clickable at all.

Sorry about that.  Bad wording when I was in a hurry due to time constraints.  Arrgh. :confounded:

Thanks for getting it sorted, and yep it works in my testing now too. :smile:
